input {
  kafka {
    bootstrap_servers => "nexus-kafka:29092"
    topics            => ["energy-metrics-iot"]
    group_id          => "logstash-iot-v3"
    auto_offset_reset => "earliest"
    consumer_threads  => 1
    codec             => json {
      target => "[@metadata][raw_json]"
    }
  }
}

filter {
  if [@metadata][raw_json] {
    ruby {
      code => "
        raw = event.get('[@metadata][raw_json]')
        if raw.is_a?(Hash)
          raw.each { |k, v| event.set(k, v) }
        end
      "
    }
  }
  # On extrait le vrai timestamp du simulateur pour écraser le @timestamp de Logstash
  if [timestamp] {
    date {
      match => [ "timestamp", "ISO8601" ]
      target => "@timestamp"
    }
  }
  mutate {
    add_field => {
      "[data_stream][type]"      => "metrics"
      "[data_stream][dataset]"   => "energy.iot"
      "[data_stream][namespace]" => "default"
    }
  }

  mutate {
    convert => {
      "wind_speed"   => "float"
      "power_output" => "float"
      "turbine_id"   => "string"
      "status"       => "string"
    }
  }
}

output {
  pipeline {
    send_to => ["central-elastic-sink"]
  }
}
