input {
  pipeline { address => "central-elastic-sink" }
}

output {
  elasticsearch {
    hosts => ["https://nexus-elasticsearch:9200"]
    user => "elastic"
    password => "ShellSeniorSecretKey2026"
	  ssl_enabled => true
    ssl_certificate_authorities => ["/usr/share/logstash/config/certs/ca/ca.crt"]
    action => "create"
	  data_stream => "true"
    
    # Sur l'ancienne API, cette option force Logstash à ne pas re-tenter indéfiniment l'envoi en cas de code 409
    # Cela permet de purger les messages Kafka déjà indexés.
    manage_template => false
    workers => 16
    bulk_max_size => 5

  }

# 1. INDEX SIMPLE TRADITIONNEL (Sans Data Stream, stockage classique)
  elasticsearch {
    hosts => ["https://nexus-elasticsearch:9200"]
    user => "elastic"
    password => "ShellSeniorSecretKey2026"
    ssl_enabled => true
    ssl_certificate_authorities => ["/usr/share/logstash/config/certs/ca/ca.crt"]
    
    # On désactive explicitement le mode Data Stream
    data_stream => "false"
    action => "index"
    
    # On cible un index classique
    index => "metrics-energy-classic-simple"
    workers => 16
    bulk_max_size => 1
  }
}
