input {
  file {
    path => "/var/log/energy/sftp/maintenance_*.csv"
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/sftp_sincedb"
    mode => "tail"
  }
}

filter {
  csv {
    separator => ";"
    columns => ["log_date", "technician_id", "asset_id", "action_performed", "vibration_level"]
    target   => "[log_data]"
  }
  mutate {
    add_field => {
      # type "logs" : événement discret, pas de série temporelle continue
      "[data_stream][type]"      => "logs"
      "[data_stream][dataset]"   => "energy.maintenance"
      "[data_stream][namespace]" => "default"
    }
    convert => { "[log_data][vibration_level]" => "float" }
  }
  fingerprint {
    source => ["[log_data][technician_id]"]
    target => "[log_data][technician_id_hashed]"
    method => "SHA256"
    key    => "${FINGERPRINT_KEY}"
    remove_field => ["[log_data][technician_id]"]
  }
  date {
    match  => [ "[log_data][log_date]", "yyyy-MM-dd HH:mm:ss" ]
    timezone => "Europe/Paris"
    target => "@timestamp"
    remove_field => [ "[log_data][log_date]" ]
  }
}

output {
  pipeline { send_to => "central-elastic-sink" }
}
