input {
  pipeline { address => "central-elastic-sink" }
}

output {
  elasticsearch {
    hosts => ["https://nexus-elasticsearch:9200"]
    user => "${ES_INGEST_USER}"
    password => "${ELASTIC_PASSWORD}"
	  ssl_enabled => true
    ssl_certificate_authorities => ["/usr/share/logstash/config/certs/ca/ca.crt"]
    action => "create"
	  data_stream => "true"

  }
}
